### ISSUE TITLE
Error occurred when I tried to follow the DetectNet example 

### ISSUE THREAD

**Issue by teoac** [dusty-nv/jetson-inference#235]
When I tried to follow the DetectNet example, I met the following error messages after creating Caffe Model on DIGITS.

```
Creating Layer bb-label-norm
bb-label-norm <- bbox-label
bb-label-norm <- size-block_size-block_0_split_0
bb-label-norm -> bbox-label-norm
Setting up bb-label-norm
Top shape: 2 4 40 40 (12800)
Memory required for data: 20461056
Creating layer bb-obj-norm
Creating Layer bb-obj-norm
bb-obj-norm <- bbox-label-norm
bb-obj-norm <- obj-block_obj-block_0_split_0
bb-obj-norm -> bbox-obj-label-norm
Setting up bb-obj-norm
Top shape: 2 4 40 40 (12800)
Memory required for data: 20512256
Creating layer conv1/7x7_s2
Creating Layer conv1/7x7_s2
conv1/7x7_s2 <- transformed_data
conv1/7x7_s2 -> conv1/7x7_s2
Check failed: status == CUDNN_STATUS_SUCCESS (3 vs. 0)  CUDNN_STATUS_BAD_PARAM
```

I succeeded to follow the ImageNet example, so I guess that cudnn, CUDA, and etc. are installed well.

**Comment by teoac** [comment]
I found the reason.
When I built the caffe, the version of cuDNN was 7.1.4+CUDA9.0.
But something upgraded the cuDNN from 7.1.4+CUDA9.0 to 7.1.4+CUDA9.2.
So I downgraded the cuDNN to the correct version and built the caffe again.
Then all problems are solved.
