### ISSUE TITLE
Installing PyTorch -> ImportError: libcudart.so.10.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by penizekr** [dusty-nv/jetson-inference#559]
Hello,
I have always error "ImportError: libcudart.so.10.0: cannot open shared object file: No such file or directory" during installation of Pytorch on Jetson Nano. I am going step by step according to instruction "Building the Project from Source". Similar also for Python3. How to solve it?

Thanks.

`^[[M#|I
[jetson-inference]  Package selection status:  0
[jetson-inference]  Packages selected for download:  1
[jetson-inference]  Downloading PyTorch v1.1.0 (Python 2.7)...
dpkg-query: no packages found matching python-pip
[jetson-inference]  Checking for 'python-pip' deb package...not installed
[jetson-inference]  Missing 'python-pip' deb package...installing 'python-pip' package.
Reading package lists...
Building dependency tree...
Reading state information...
The following packages were automatically installed and are no longer required:
  apt-clone archdetect-deb bogl-bterm busybox-static cryptsetup-bin
  dpkg-repack gir1.2-timezonemap-1.0 gir1.2-xkl-1.0 grub-common
  kde-window-manager kinit kio kpackagetool5 kwayland-data kwin-common
  kwin-data kwin-x11 libdebian-installer4 libkdecorations2-5v5
  libkdecorations2private5v5 libkf5activities5 libkf5attica5
  libkf5completion-data libkf5completion5 libkf5declarative-data
  libkf5declarative5 libkf5doctools5 libkf5globalaccel-data libkf5globalaccel5
  libkf5globalaccelprivate5 libkf5idletime5 libkf5jobwidgets-data
  libkf5jobwidgets5 libkf5kcmutils-data libkf5kcmutils5 libkf5kiocore5
  libkf5kiontlm5 libkf5kiowidgets5 libkf5newstuff-data libkf5newstuff5
  libkf5newstuffcore5 libkf5package-data libkf5package5 libkf5plasma5
  libkf5quickaddons5 libkf5solid5 libkf5solid5-data libkf5sonnet5-data
  libkf5sonnetcore5 libkf5sonnetui5 libkf5textwidgets-data libkf5textwidgets5
  libkf5waylandclient5 libkf5waylandserver5 libkf5xmlgui-bin libkf5xmlgui-data
  libkf5xmlgui5 libkscreenlocker5 libkwin4-effect-builtins1 libkwineffects11
  libkwinglutils11 libkwinxrenderutils11 libqgsttools-p1 libqt5designer5
  libqt5help5 libqt5multimedia5 libqt5multimedia5-plugins
  libqt5multimediaquick-p5 libqt5multimediawidgets5 libqt5opengl5
  libqt5positioning5 libqt5printsupport5 libqt5qml5 libqt5quick5
  libqt5quickwidgets5 libqt5sensors5 libqt5sql5 libqt5test5 libqt5webchannel5
  libqt5webkit5 libxcb-composite0 libxcb-cursor0 libxcb-damage0 os-prober
  python3-dbus.mainloop.pyqt5 python3-icu python3-pam python3-pyqt5
  python3-pyqt5.qtsvg python3-pyqt5.qtwebkit python3-sip
  qml-module-org-kde-kquickcontrolsaddons qml-module-qtmultimedia
  qml-module-qtquick2 rdate tasksel tasksel-data
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  libpython-all-dev python-all python-all-dev python-asn1crypto
  python-cffi-backend python-crypto python-cryptography python-enum34
  python-idna python-ipaddress python-keyring python-keyrings.alt
  python-pip-whl python-secretstorage python-setuptools python-wheel
  python-xdg
Suggested packages:
  python-crypto-doc python-cryptography-doc python-cryptography-vectors
  python-enum34-doc gir1.2-gnomekeyring-1.0 python-fs python-gdata
  python-keyczar python-secretstorage-doc python-setuptools-doc
The following NEW packages will be installed:
  libpython-all-dev python-all python-all-dev python-asn1crypto
  python-cffi-backend python-crypto python-cryptography python-enum34
  python-idna python-ipaddress python-keyring python-keyrings.alt python-pip
  python-pip-whl python-secretstorage python-setuptools python-wheel
  python-xdg
0 upgraded, 18 newly installed, 0 to remove and 131 not upgraded.
Need to get 2 894 kB of archives.
After this operation, 8 742 kB of additional disk space will be used.
Get:1 http://ports.ubuntu.com/ubuntu-ports bionic/main arm64 libpython-all-dev arm64 2.7.15~rc1-1 [1 092 B]
Get:2 http://ports.ubuntu.com/ubuntu-ports bionic/main arm64 python-all arm64 2.7.15~rc1-1 [1 076 B]
Get:3 http://ports.ubuntu.com/ubuntu-ports bionic/main arm64 python-all-dev arm64 2.7.15~rc1-1 [1 100 B]
Get:4 http://ports.ubuntu.com/ubuntu-ports bionic/main arm64 python-asn1crypto all 0.24.0-1 [72,7 kB]
Get:5 http://ports.ubuntu.com/ubuntu-ports bionic/main arm64 python-cffi-backend arm64 1.11.5-1 [59,2 kB]
Get:6 http://ports.ubuntu.com/ubuntu-ports bionic/main arm64 python-crypto arm64 2.6.1-8ubuntu2 [240 kB]
Get:7 http://ports.ubuntu.com/ubuntu-ports bionic/main arm64 python-enum34 all 1.1.6-2 [34,8 kB]
Get:8 http://ports.ubuntu.com/ubuntu-ports bionic/main arm64 python-idna all 2.6-1 [32,4 kB]
Get:9 http://ports.ubuntu.com/ubuntu-ports bionic/main arm64 python-ipaddress all 1.0.17-1 [18,2 kB]
Get:10 http://ports.ubuntu.com/ubuntu-ports bionic-updates/main arm64 python-cryptography arm64 2.1.4-1ubuntu1.3 [175 kB]
Get:11 http://ports.ubuntu.com/ubuntu-ports bionic/main arm64 python-secretstorage all 2.3.1-2 [11,8 kB]
Get:12 http://ports.ubuntu.com/ubuntu-ports bionic/main arm64 python-keyring all 10.6.0-1 [30,6 kB]
Get:13 http://ports.ubuntu.com/ubuntu-ports bionic/main arm64 python-keyrings.alt all 3.0-1 [16,7 kB]
Get:14 http://ports.ubuntu.com/ubuntu-ports bionic-updates/universe arm64 python-pip-whl all 9.0.1-2.3~ubuntu1.18.04.1 [1 653 kB]
Get:15 http://ports.ubuntu.com/ubuntu-ports bionic-updates/universe arm64 python-pip all 9.0.1-2.3~ubuntu1.18.04.1 [151 kB]
Get:16 http://ports.ubuntu.com/ubuntu-ports bionic/main arm64 python-setuptools all 39.0.1-2 [329 kB]
Get:17 http://ports.ubuntu.com/ubuntu-ports bionic/universe arm64 python-wheel all 0.30.0-0.2 [36,4 kB]
Get:18 http://ports.ubuntu.com/ubuntu-ports bionic/universe arm64 python-xdg all 0.25-4ubuntu1 [31,3 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 2 894 kB in 2s (1 165 kB/s)
                                   Selecting previously unselected package libpython-all-dev:arm64.
(Reading database ... 141845 files and directories currently installed.)
Preparing to unpack .../00-libpython-all-dev_2.7.15~rc1-1_arm64.deb ...
Unpacking libpython-all-dev:arm64 (2.7.15~rc1-1) ...
Selecting previously unselected package python-all.
Preparing to unpack .../01-python-all_2.7.15~rc1-1_arm64.deb ...
Unpacking python-all (2.7.15~rc1-1) ...
Selecting previously unselected package python-all-dev.
Preparing to unpack .../02-python-all-dev_2.7.15~rc1-1_arm64.deb ...
Unpacking python-all-dev (2.7.15~rc1-1) ...
Selecting previously unselected package python-asn1crypto.
Preparing to unpack .../03-python-asn1crypto_0.24.0-1_all.deb ...
Unpacking python-asn1crypto (0.24.0-1) ...
Selecting previously unselected package python-cffi-backend.
Preparing to unpack .../04-python-cffi-backend_1.11.5-1_arm64.deb ...
Unpacking python-cffi-backend (1.11.5-1) ...
Selecting previously unselected package python-crypto.
Preparing to unpack .../05-python-crypto_2.6.1-8ubuntu2_arm64.deb ...
Unpacking python-crypto (2.6.1-8ubuntu2) ...
Selecting previously unselected package python-enum34.
Preparing to unpack .../06-python-enum34_1.1.6-2_all.deb ...
Unpacking python-enum34 (1.1.6-2) ...
Selecting previously unselected package python-idna.
Preparing to unpack .../07-python-idna_2.6-1_all.deb ...
Unpacking python-idna (2.6-1) ...
Selecting previously unselected package python-ipaddress.
Preparing to unpack .../08-python-ipaddress_1.0.17-1_all.deb ...
Unpacking python-ipaddress (1.0.17-1) ...
Selecting previously unselected package python-cryptography.
Preparing to unpack .../09-python-cryptography_2.1.4-1ubuntu1.3_arm64.deb ...
Unpacking python-cryptography (2.1.4-1ubuntu1.3) ...
Selecting previously unselected package python-secretstorage.
Preparing to unpack .../10-python-secretstorage_2.3.1-2_all.deb ...
Unpacking python-secretstorage (2.3.1-2) ...
Selecting previously unselected package python-keyring.
Preparing to unpack .../11-python-keyring_10.6.0-1_all.deb ...
Unpacking python-keyring (10.6.0-1) ...
Selecting previously unselected package python-keyrings.alt.
Preparing to unpack .../12-python-keyrings.alt_3.0-1_all.deb ...
Unpacking python-keyrings.alt (3.0-1) ...
Selecting previously unselected package python-pip-whl.
Preparing to unpack .../13-python-pip-whl_9.0.1-2.3~ubuntu1.18.04.1_all.deb ...
Unpacking python-pip-whl (9.0.1-2.3~ubuntu1.18.04.1) ...
Selecting previously unselected package python-pip.
Preparing to unpack .../14-python-pip_9.0.1-2.3~ubuntu1.18.04.1_all.deb ...
Unpacking python-pip (9.0.1-2.3~ubuntu1.18.04.1) ...
Selecting previously unselected package python-setuptools.
Preparing to unpack .../15-python-setuptools_39.0.1-2_all.deb ...
Unpacking python-setuptools (39.0.1-2) ...
Selecting previously unselected package python-wheel.
Preparing to unpack .../16-python-wheel_0.30.0-0.2_all.deb ...
Unpacking python-wheel (0.30.0-0.2) ...
Selecting previously unselected package python-xdg.
Preparing to unpack .../17-python-xdg_0.25-4ubuntu1_all.deb ...
Unpacking python-xdg (0.25-4ubuntu1) ...
Setting up python-idna (2.6-1) ...
Setting up python-pip-whl (9.0.1-2.3~ubuntu1.18.04.1) ...
Setting up python-setuptools (39.0.1-2) ...
Setting up python-asn1crypto (0.24.0-1) ...
Setting up python-crypto (2.6.1-8ubuntu2) ...
Setting up python-wheel (0.30.0-0.2) ...
Setting up libpython-all-dev:arm64 (2.7.15~rc1-1) ...
Setting up python-keyrings.alt (3.0-1) ...
Setting up python-cffi-backend (1.11.5-1) ...
Setting up python-enum34 (1.1.6-2) ...
Setting up python-ipaddress (1.0.17-1) ...
Setting up python-pip (9.0.1-2.3~ubuntu1.18.04.1) ...
Setting up python-all (2.7.15~rc1-1) ...
Setting up python-xdg (0.25-4ubuntu1) ...
Setting up python-all-dev (2.7.15~rc1-1) ...
Setting up python-cryptography (2.1.4-1ubuntu1.3) ...
Setting up python-secretstorage (2.3.1-2) ...
Setting up python-keyring (10.6.0-1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
W: --force-yes is deprecated, use one of the options starting with --allow instead.
[jetson-inference]  Checking for 'python-pip' deb package...installed
[jetson-inference]  Successfully installed 'python-pip' deb package.
dpkg-query: no packages found matching qtbase5-dev
[jetson-inference]  Checking for 'qtbase5-dev' deb package...not installed
[jetson-inference]  Missing 'qtbase5-dev' deb package...installing 'qtbase5-dev' package.
Reading package lists...
Building dependency tree...
Reading state information...
The following packages were automatically installed and are no longer required:
  apt-clone archdetect-deb bogl-bterm busybox-static cryptsetup-bin
  dpkg-repack gir1.2-timezonemap-1.0 gir1.2-xkl-1.0 grub-common
  kde-window-manager kinit kio kpackagetool5 kwayland-data kwin-common
  kwin-data kwin-x11 libdebian-installer4 libkdecorations2-5v5
  libkdecorations2private5v5 libkf5activities5 libkf5attica5
  libkf5completion-data libkf5completion5 libkf5declarative-data
  libkf5declarative5 libkf5doctools5 libkf5globalaccel-data libkf5globalaccel5
  libkf5globalaccelprivate5 libkf5idletime5 libkf5jobwidgets-data
  libkf5jobwidgets5 libkf5kcmutils-data libkf5kcmutils5 libkf5kiocore5
  libkf5kiontlm5 libkf5kiowidgets5 libkf5newstuff-data libkf5newstuff5
  libkf5newstuffcore5 libkf5package-data libkf5package5 libkf5plasma5
  libkf5quickaddons5 libkf5solid5 libkf5solid5-data libkf5sonnet5-data
  libkf5sonnetcore5 libkf5sonnetui5 libkf5textwidgets-data libkf5textwidgets5
  libkf5waylandclient5 libkf5waylandserver5 libkf5xmlgui-bin libkf5xmlgui-data
  libkf5xmlgui5 libkscreenlocker5 libkwin4-effect-builtins1 libkwineffects11
  libkwinglutils11 libkwinxrenderutils11 libqgsttools-p1 libqt5designer5
  libqt5help5 libqt5multimedia5 libqt5multimedia5-plugins
  libqt5multimediaquick-p5 libqt5multimediawidgets5 libqt5positioning5
  libqt5qml5 libqt5quick5 libqt5quickwidgets5 libqt5sensors5 libqt5webchannel5
  libqt5webkit5 libxcb-composite0 libxcb-cursor0 libxcb-damage0 os-prober
  python3-dbus.mainloop.pyqt5 python3-icu python3-pam python3-pyqt5
  python3-pyqt5.qtsvg python3-pyqt5.qtwebkit python3-sip
  qml-module-org-kde-kquickcontrolsaddons qml-module-qtmultimedia
  qml-module-qtquick2 rdate tasksel tasksel-data
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  libqt5concurrent5 libqt5opengl5-dev qt5-qmake qt5-qmake-bin
  qtbase5-dev-tools
Suggested packages:
  default-libmysqlclient-dev firebird-dev libpq-dev libsqlite3-dev
  unixodbc-dev
The following NEW packages will be installed:
  libqt5concurrent5 libqt5opengl5-dev qt5-qmake qt5-qmake-bin qtbase5-dev
  qtbase5-dev-tools
0 upgraded, 6 newly installed, 0 to remove and 131 not upgraded.
Need to get 2 597 kB of archives.
After this operation, 20,5 MB of additional disk space will be used.
Get:1 http://ports.ubuntu.com/ubuntu-ports bionic-updates/main arm64 libqt5concurrent5 arm64 5.9.5+dfsg-0ubuntu2.5 [29,5 kB]
Get:2 http://ports.ubuntu.com/ubuntu-ports bionic-updates/main arm64 qt5-qmake-bin arm64 5.9.5+dfsg-0ubuntu2.5 [848 kB]
Get:3 http://ports.ubuntu.com/ubuntu-ports bionic-updates/main arm64 qt5-qmake arm64 5.9.5+dfsg-0ubuntu2.5 [180 kB]
Get:4 http://ports.ubuntu.com/ubuntu-ports bionic-updates/main arm64 qtbase5-dev-tools arm64 5.9.5+dfsg-0ubuntu2.5 [609 kB]
Get:5 http://ports.ubuntu.com/ubuntu-ports bionic-updates/main arm64 qtbase5-dev arm64 5.9.5+dfsg-0ubuntu2.5 [894 kB]
Get:6 http://ports.ubuntu.com/ubuntu-ports bionic-updates/main arm64 libqt5opengl5-dev arm64 5.9.5+dfsg-0ubuntu2.5 [36,0 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 2 597 kB in 2s (1 047 kB/s)
                                   Selecting previously unselected package libqt5concurrent5:arm64.
(Reading database ... 142562 files and directories currently installed.)
Preparing to unpack .../0-libqt5concurrent5_5.9.5+dfsg-0ubuntu2.5_arm64.deb ...
Unpacking libqt5concurrent5:arm64 (5.9.5+dfsg-0ubuntu2.5) ...
Selecting previously unselected package qt5-qmake-bin.
Preparing to unpack .../1-qt5-qmake-bin_5.9.5+dfsg-0ubuntu2.5_arm64.deb ...
Unpacking qt5-qmake-bin (5.9.5+dfsg-0ubuntu2.5) ...
Selecting previously unselected package qt5-qmake:arm64.
Preparing to unpack .../2-qt5-qmake_5.9.5+dfsg-0ubuntu2.5_arm64.deb ...
Unpacking qt5-qmake:arm64 (5.9.5+dfsg-0ubuntu2.5) ...
Selecting previously unselected package qtbase5-dev-tools.
Preparing to unpack .../3-qtbase5-dev-tools_5.9.5+dfsg-0ubuntu2.5_arm64.deb ...
Unpacking qtbase5-dev-tools (5.9.5+dfsg-0ubuntu2.5) ...
Selecting previously unselected package qtbase5-dev:arm64.
Preparing to unpack .../4-qtbase5-dev_5.9.5+dfsg-0ubuntu2.5_arm64.deb ...
Unpacking qtbase5-dev:arm64 (5.9.5+dfsg-0ubuntu2.5) ...
Selecting previously unselected package libqt5opengl5-dev:arm64.
Preparing to unpack .../5-libqt5opengl5-dev_5.9.5+dfsg-0ubuntu2.5_arm64.deb ...
Unpacking libqt5opengl5-dev:arm64 (5.9.5+dfsg-0ubuntu2.5) ...
Setting up qtbase5-dev-tools (5.9.5+dfsg-0ubuntu2.5) ...
Setting up qt5-qmake-bin (5.9.5+dfsg-0ubuntu2.5) ...
Setting up qt5-qmake:arm64 (5.9.5+dfsg-0ubuntu2.5) ...
Setting up libqt5concurrent5:arm64 (5.9.5+dfsg-0ubuntu2.5) ...
Setting up qtbase5-dev:arm64 (5.9.5+dfsg-0ubuntu2.5) ...
Setting up libqt5opengl5-dev:arm64 (5.9.5+dfsg-0ubuntu2.5) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
W: --force-yes is deprecated, use one of the options starting with --allow instead.
[jetson-inference]  Checking for 'qtbase5-dev' deb package...installed
[jetson-inference]  Successfully installed 'qtbase5-dev' deb package.
dpkg-query: no packages found matching libjpeg-dev
[jetson-inference]  Checking for 'libjpeg-dev' deb package...not installed
[jetson-inference]  Missing 'libjpeg-dev' deb package...installing 'libjpeg-dev' package.
Reading package lists...
Building dependency tree...
Reading state information...
The following packages were automatically installed and are no longer required:
  apt-clone archdetect-deb bogl-bterm busybox-static cryptsetup-bin
  dpkg-repack gir1.2-timezonemap-1.0 gir1.2-xkl-1.0 grub-common
  kde-window-manager kinit kio kpackagetool5 kwayland-data kwin-common
  kwin-data kwin-x11 libdebian-installer4 libkdecorations2-5v5
  libkdecorations2private5v5 libkf5activities5 libkf5attica5
  libkf5completion-data libkf5completion5 libkf5declarative-data
  libkf5declarative5 libkf5doctools5 libkf5globalaccel-data libkf5globalaccel5
  libkf5globalaccelprivate5 libkf5idletime5 libkf5jobwidgets-data
  libkf5jobwidgets5 libkf5kcmutils-data libkf5kcmutils5 libkf5kiocore5
  libkf5kiontlm5 libkf5kiowidgets5 libkf5newstuff-data libkf5newstuff5
  libkf5newstuffcore5 libkf5package-data libkf5package5 libkf5plasma5
  libkf5quickaddons5 libkf5solid5 libkf5solid5-data libkf5sonnet5-data
  libkf5sonnetcore5 libkf5sonnetui5 libkf5textwidgets-data libkf5textwidgets5
  libkf5waylandclient5 libkf5waylandserver5 libkf5xmlgui-bin libkf5xmlgui-data
  libkf5xmlgui5 libkscreenlocker5 libkwin4-effect-builtins1 libkwineffects11
  libkwinglutils11 libkwinxrenderutils11 libqgsttools-p1 libqt5designer5
  libqt5help5 libqt5multimedia5 libqt5multimedia5-plugins
  libqt5multimediaquick-p5 libqt5multimediawidgets5 libqt5positioning5
  libqt5qml5 libqt5quick5 libqt5quickwidgets5 libqt5sensors5 libqt5webchannel5
  libqt5webkit5 libxcb-composite0 libxcb-cursor0 libxcb-damage0 os-prober
  python3-dbus.mainloop.pyqt5 python3-icu python3-pam python3-pyqt5
  python3-pyqt5.qtsvg python3-pyqt5.qtwebkit python3-sip
  qml-module-org-kde-kquickcontrolsaddons qml-module-qtmultimedia
  qml-module-qtquick2 rdate tasksel tasksel-data
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  libjpeg-turbo8-dev libjpeg8-dev
The following NEW packages will be installed:
  libjpeg-dev libjpeg-turbo8-dev libjpeg8-dev
0 upgraded, 3 newly installed, 0 to remove and 131 not upgraded.
Need to get 207 kB of archives.
After this operation, 601 kB of additional disk space will be used.
Get:1 http://ports.ubuntu.com/ubuntu-ports bionic-updates/main arm64 libjpeg-turbo8-dev arm64 1.5.2-0ubuntu5.18.04.3 [203 kB]
Get:2 http://ports.ubuntu.com/ubuntu-ports bionic/main arm64 libjpeg8-dev arm64 8c-2ubuntu8 [1 550 B]
Get:3 http://ports.ubuntu.com/ubuntu-ports bionic/main arm64 libjpeg-dev arm64 8c-2ubuntu8 [1 546 B]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 207 kB in 1s (330 kB/s)
                               Selecting previously unselected package libjpeg-turbo8-dev:arm64.
(Reading database ... 145019 files and directories currently installed.)
Preparing to unpack .../libjpeg-turbo8-dev_1.5.2-0ubuntu5.18.04.3_arm64.deb ...
Unpacking libjpeg-turbo8-dev:arm64 (1.5.2-0ubuntu5.18.04.3) ...
Selecting previously unselected package libjpeg8-dev:arm64.
Preparing to unpack .../libjpeg8-dev_8c-2ubuntu8_arm64.deb ...
Unpacking libjpeg8-dev:arm64 (8c-2ubuntu8) ...
Selecting previously unselected package libjpeg-dev:arm64.
Preparing to unpack .../libjpeg-dev_8c-2ubuntu8_arm64.deb ...
Unpacking libjpeg-dev:arm64 (8c-2ubuntu8) ...
Setting up libjpeg-turbo8-dev:arm64 (1.5.2-0ubuntu5.18.04.3) ...
Setting up libjpeg8-dev:arm64 (8c-2ubuntu8) ...
Setting up libjpeg-dev:arm64 (8c-2ubuntu8) ...
W: --force-yes is deprecated, use one of the options starting with --allow instead.
[jetson-inference]  Checking for 'libjpeg-dev' deb package...installed
[jetson-inference]  Successfully installed 'libjpeg-dev' deb package.
[jetson-inference]  Checking for 'zlib1g-dev' deb package...installed
torch-1.1.0-cp27-cp 100%[===================>] 202,37M  1,15MB/s    in 3m 36s  
Processing ./torch-1.1.0-cp27-cp27mu-linux_aarch64.whl
Collecting numpy (from torch==1.1.0)
  Downloading https://files.pythonhosted.org/packages/b7/6f/24647f014eef9b67a24adfcbcd4f4928349b4a0f8393b3d7fe648d4d2de3/numpy-1.16.6.zip (5.1MB)
Collecting future (from torch==1.1.0)
  Downloading https://files.pythonhosted.org/packages/45/0b/38b06fd9b92dc2b68d58b75f900e97884c45bedd2ff83203d933cf5851c9/future-0.18.2.tar.gz (829kB)
Building wheels for collected packages: numpy, future
  Running setup.py bdist_wheel for numpy: started
  Running setup.py bdist_wheel for numpy: still running...
  Running setup.py bdist_wheel for numpy: still running...
  Running setup.py bdist_wheel for numpy: finished with status 'done'
  Stored in directory: /home/rp/.cache/pip/wheels/cb/c2/c1/d99e8bf789c8dd07623af6be95e6a89984c85a05e31b8513c3
  Running setup.py bdist_wheel for future: started
  Running setup.py bdist_wheel for future: finished with status 'done'

  Stored in directory: /home/rp/.cache/pip/wheels/8b/99/a0/81daf51dcd359a9377b110a8a886b3895921802d2fc1b2397e
Successfully built numpy future
Installing collected packages: numpy, future, torch
Successfully installed future-0.18.2 numpy-1.16.6 torch-1.1.0
[jetson-inference]  cloning torchvision...
Cloning into 'torchvision-27'...
[jetson-inference]  building torchvision for Python 3.6...
Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    import torch
  File "/home/rp/.local/lib/python2.7/site-packages/torch/__init__.py", line 79, in <module>
    from torch._C import *
ImportError: libcudart.so.10.0: cannot open shared object file: No such file or directory
Collecting pillow<7
  Downloading https://files.pythonhosted.org/packages/b3/d0/a20d8440b71adfbf133452d4f6e0fe80de2df7c2578c9b498fb812083383/Pillow-6.2.2.tar.gz (37.8MB)
Building wheels for collected packages: pillow
  Running setup.py bdist_wheel for pillow: started
  Running setup.py bdist_wheel for pillow: finished with status 'done'
  Stored in directory: /home/rp/.cache/pip/wheels/f6/0a/7c/5e6567101a10388b915c4ebf73edb849f73908ad154e9eb9bc
Successfully built pillow
Installing collected packages: pillow
Successfully installed pillow-6.2.2
 
[jetson-inference]  installation complete, exiting with status code 0
[jetson-inference]  to run this tool again, use the following commands:
 
    $ cd <jetson-inference>/build
    $ ./install-pytorch.sh
 
[Pre-build]  Finished CMakePreBuild script
-- Finished installing dependencies
-- using patched FindCUDA.cmake
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found version "10.2") 
-- CUDA version: 10.2
-- CUDA 10 detected, enabling SM_72
-- Found OpenCV: /usr (found version "4.1.1") found components:  core calib3d 
-- OpenCV version:  4.1.1
-- OpenCV version >= 3.0.0, enabling OpenCV
-- system arch:  aarch64
-- output path:  /home/rp/jetson-inference/build/aarch64
-- Copying /home/rp/jetson-inference/c/detectNet.h
-- Copying /home/rp/jetson-inference/c/homographyNet.h
-- Copying /home/rp/jetson-inference/c/imageNet.h
-- Copying /home/rp/jetson-inference/c/segNet.h
-- Copying /home/rp/jetson-inference/c/superResNet.h
-- Copying /home/rp/jetson-inference/c/tensorNet.h
-- Copying /home/rp/jetson-inference/c/imageNet.cuh
-- Copying /home/rp/jetson-inference/calibration/randInt8Calibrator.h
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- found Qt5Widgets version:  5.9.5
-- found Qt5Widgets defines:  -DQT_WIDGETS_LIB;-DQT_GUI_LIB;-DQT_CORE_LIB
-- found Qt5Widgets library:  Qt5::Widgets
-- found Qt5Widgets include:  /usr/include/aarch64-linux-gnu/qt5/;/usr/include/aarch64-linux-gnu/qt5/QtWidgets;/usr/include/aarch64-linux-gnu/qt5/QtGui;/usr/include/aarch64-linux-gnu/qt5/QtCore;/usr/lib/aarch64-linux-gnu/qt5//mkspecs/linux-g++
-- camera-capture:  building as submodule, /home/rp/jetson-inference/tools
-- jetson-utils:  building as submodule, /home/rp/jetson-inference
-- Copying /home/rp/jetson-inference/utils/XML.h
-- Copying /home/rp/jetson-inference/utils/commandLine.h
-- Copying /home/rp/jetson-inference/utils/filesystem.h
-- Copying /home/rp/jetson-inference/utils/mat33.h
-- Copying /home/rp/jetson-inference/utils/pi.h
-- Copying /home/rp/jetson-inference/utils/rand.h
-- Copying /home/rp/jetson-inference/utils/timespec.h
-- Copying /home/rp/jetson-inference/utils/camera/gstCamera.h
-- Copying /home/rp/jetson-inference/utils/camera/v4l2Camera.h
-- Copying /home/rp/jetson-inference/utils/codec/gstDecoder.h
-- Copying /home/rp/jetson-inference/utils/codec/gstEncoder.h
-- Copying /home/rp/jetson-inference/utils/codec/gstUtility.h
-- Copying /home/rp/jetson-inference/utils/cuda/cudaFont.h
-- Copying /home/rp/jetson-inference/utils/cuda/cudaMappedMemory.h
-- Copying /home/rp/jetson-inference/utils/cuda/cudaNormalize.h
-- Copying /home/rp/jetson-inference/utils/cuda/cudaOverlay.h
-- Copying /home/rp/jetson-inference/utils/cuda/cudaRGB.h
-- Copying /home/rp/jetson-inference/utils/cuda/cudaResize.h
-- Copying /home/rp/jetson-inference/utils/cuda/cudaUtility.h
-- Copying /home/rp/jetson-inference/utils/cuda/cudaWarp.h
-- Copying /home/rp/jetson-inference/utils/cuda/cudaYUV.h
-- Copying /home/rp/jetson-inference/utils/display/glDisplay.h
-- Copying /home/rp/jetson-inference/utils/display/glTexture.h
-- Copying /home/rp/jetson-inference/utils/display/glUtility.h
-- Copying /home/rp/jetson-inference/utils/image/imageIO.h
-- Copying /home/rp/jetson-inference/utils/image/loadImage.h
-- Copying /home/rp/jetson-inference/utils/input/devInput.h
-- Copying /home/rp/jetson-inference/utils/input/devJoystick.h
-- Copying /home/rp/jetson-inference/utils/input/devKeyboard.h
-- Copying /home/rp/jetson-inference/utils/network/Endian.h
-- Copying /home/rp/jetson-inference/utils/network/IPv4.h
-- Copying /home/rp/jetson-inference/utils/network/NetworkAdapter.h
-- Copying /home/rp/jetson-inference/utils/network/Socket.h
-- Copying /home/rp/jetson-inference/utils/threads/Event.h
-- Copying /home/rp/jetson-inference/utils/threads/Mutex.h
-- Copying /home/rp/jetson-inference/utils/threads/Process.h
-- Copying /home/rp/jetson-inference/utils/threads/Thread.h
-- trying to build Python bindings for Python versions:  2.7;3.6;3.7
-- detecting Python 2.7...
-- found Python version:  2.7 (2.7.17)
-- found Python include:  /usr/include/python2.7
-- found Python library:  /usr/lib/aarch64-linux-gnu/libpython2.7.so
-- CMake module path:  /home/rp/jetson-inference/utils/cuda;/home/rp/jetson-inference/utils/python/bindings
-- NumPy ver. 1.16.6 found (include: /home/rp/.local/lib/python2.7/site-packages/numpy/core/include)
-- found NumPy version:  1.16.6
-- found NumPy include:  /home/rp/.local/lib/python2.7/site-packages/numpy/core/include
-- detecting Python 3.6...
-- found Python version:  3.6 (3.6.9)
-- found Python include:  /usr/include/python3.6m
-- found Python library:  /usr/lib/aarch64-linux-gnu/libpython3.6m.so
-- CMake module path:  /home/rp/jetson-inference/utils/cuda;/home/rp/jetson-inference/utils/python/bindings
-- NumPy ver. 1.13.3 found (include: /usr/lib/python3/dist-packages/numpy/core/include)
-- found NumPy version:  1.13.3
-- found NumPy include:  /usr/lib/python3/dist-packages/numpy/core/include
-- detecting Python 3.7...
-- Python 3.7 wasn't found
-- Copying /home/rp/jetson-inference/utils/python/examples/camera-viewer.py
-- Copying /home/rp/jetson-inference/utils/python/examples/cuda-from-numpy.py
-- Copying /home/rp/jetson-inference/utils/python/examples/cuda-to-numpy.py
-- Copying /home/rp/jetson-inference/utils/python/examples/gl-display-test.py
-- trying to build Python bindings for Python versions:  2.7;3.6;3.7
-- detecting Python 2.7...
-- found Python version:  2.7 (2.7.17)
-- found Python include:  /usr/include/python2.7
-- found Python library:  /usr/lib/aarch64-linux-gnu/libpython2.7.so
-- detecting Python 3.6...
-- found Python version:  3.6 (3.6.9)
-- found Python include:  /usr/include/python3.6m
-- found Python library:  /usr/lib/aarch64-linux-gnu/libpython3.6m.so
-- detecting Python 3.7...
-- Python 3.7 wasn't found
-- Copying /home/rp/jetson-inference/python/examples/detectnet-camera.py
-- Copying /home/rp/jetson-inference/python/examples/detectnet-console.py
-- Copying /home/rp/jetson-inference/python/examples/imagenet-camera.py
-- Copying /home/rp/jetson-inference/python/examples/imagenet-console.py
-- Copying /home/rp/jetson-inference/python/examples/my-detection.py
-- Copying /home/rp/jetson-inference/python/examples/my-recognition.py
-- Copying /home/rp/jetson-inference/python/examples/segnet-batch.py
-- Copying /home/rp/jetson-inference/python/examples/segnet-camera.py
-- Copying /home/rp/jetson-inference/python/examples/segnet-console.py
-- Linking jetson-inference with OpenCV 4.1.1
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rp/jetson-inference/build`

**Comment by dusty-nv** [comment]
Hi @penizekr, are you on JetPack 4.4?   Sorry, the script needs updated for that.  Can you uninstall torch/torchvision pip/pip3 packages and instead install from here please?   https://forums.developer.nvidia.com/t/pytorch-for-jetson-nano-version-1-5-0-now-available/72048/261

**Comment by penizekr** [comment]
Hi, how to find which version of JetPack I have?

**Comment by penizekr** [comment]
Which version of PyTorch should I install? Thanks.

**Comment by dusty-nv** [comment]
You can determine your JetPack version with this terminal command:

```
dpkg-query --showformat='${Version}' --show nvidia-l4t-core
```

If that doesn't work, run `cat /etc/nv_tegra_release`

These commands will print out the L4T version (let me know what that is for you), which corresponds to the JetPack version.  Try using PyTorch 1.2 for your appropriate version of JetPack.

**Comment by penizekr** [comment]
First command returned:
32.4.2-20200408182156

Second command:
# R32 (release), REVISION: 4.2, GCID: 20074772, BOARD: t210ref, EABI: aarch64, DATE: Thu Apr  9 01:22:12 UTC 2020

**Comment by dusty-nv** [comment]
OK, use these wheels for JetPack 4.4:

Python 2.7 [`torch-1.2.0-cp27-cp27mu-linux_aarch64.whl`](https://nvidia.box.com/shared/static/8673jprub45abv3tmx4sscdllpbinoh9.whl)
Python 3.6 [` torch-1.2.0-cp36-cp36m-linux_aarch64.whl`](https://nvidia.box.com/shared/static/lufbgr3xu2uha40cs9ryq1zn4kxsnogl.whl)

The install instructions for PyTorch and torchvision are on this page:  https://forums.developer.nvidia.com/t/pytorch-for-jetson-nano-version-1-5-0-now-available/72048/1

You will want to install torchvision v0.4.0 since it is with PyTorch 1.2.

**Comment by penizekr** [comment]
OK, thanks. I will try it.

**Comment by penizekr** [comment]
During installation of torchvision I got an error after comman  "sudo python setup.py install" :

Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    import torch
  File "/home/rp/.local/lib/python2.7/site-packages/torch/__init__.py", line 81, in <module>
    from torch._C import *
ImportError: libmpi_cxx.so.20: cannot open shared object file: No such file or directory

**Comment by penizekr** [comment]
Same error in python after "import torch" 

>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rp/.local/lib/python2.7/site-packages/torch/__init__.py", line 81, in <module>
    from torch._C import *
ImportError: libmpi_cxx.so.20: cannot open shared object file: No such file or directory
>>>

**Comment by penizekr** [comment]
These problems I have with  Jetson nano image from 2020/04/21 (JP4.4). Would you recommend to use version from 2019/12/17 (JP4.3) to avoid the problems?

**Comment by dusty-nv** [comment]
> Would you recommend to use version from 2019/12/17 (JP4.3) to avoid the problems?

For JP 4.3, you would need to use the JetPack 4.3 version of the PyTorch wheels.   But these do work on Nano with JP 4.4, perhaps you are just missing MPI (which is typically installed by default).  Can you try installing `libopenmpi-dev`:

`sudo apt-get install libopenmpi-dev`

**Comment by penizekr** [comment]
I can confirm step forward. After installation of libopenmpi-dev I can run "import torch" and verify version.
Now is running "sudo python setup.py install" for torchvision. With many warnings.

rp@rp-desktop:~$ python
Python 2.7.17 (default, Nov  7 2019, 10:07:09) 
[GCC 7.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.__version__)
1.2.0

**Comment by dusty-nv** [comment]
Thanks, I have added `libopenmpi-dev` to the instructions on the forum just in case other users encounter that too.

**Comment by penizekr** [comment]
torchvision verification shows:

Python 2.7.17 (default, Nov  7 2019, 10:07:09) 
[GCC 7.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import torchvision
>>> print(torchvision.__version__)
0.4.1a0+a263704

**Comment by penizekr** [comment]
It works now. Thanks for quick help!
BR
Radek
