### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by long-light** [dusty-nv/jetson-inference#812]
Why does the following error occur when training the model with AGX xavier:
RuntimeError: CUDA error: no kernel image is available for execution on the device
pytorch 1.6 + torchvision 0.7 +cuda10.2

**Comment by dusty-nv** [comment]
Hmm I'm not sure why that would happen, because the PyTorch wheels were built with SM_72 enabled (in addition to SM_53 and SM_62)

Which model are you training?     And are you running the container or did you build from source?   Also, which version of JetPack are you on?

**Comment by long-light** [comment]
I am using JetPack 4.4 and I am training SSD-Mobilenet. I solved this error by recompiling pytorch 1.6 version. Thank you
